name: design_ideaz_app
description: "Design Ideaz E-Learning Platform"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - asset/images/desiznideaz_logo.png

flutter_native_splash:
  color: "#FFFFFF"
  image: asset/images/desiznideaz_logo.png
  android: true
  ios: true
