import 'package:design_ideaz_app/screens/course_overview_screen.dart';

final List<Course> courses = [
  Course(
    title: 'Web design fundamentals',
    duration: '8h 30min',
    lessonCount: 32,
    rating: 4.8,
    imageUrl: 'https://img.youtube.com/vi/C72WkcUZvco/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Introduction to Web Design', duration: '45min'),
      Lesson(title: 'HTML Basics', duration: '1h 30min'),
    ],
    price: 49.99,
  ),
  Course(
    title: 'Figma Master Class',
    duration: '6h30m',
    lessonCount: 28,
    rating: 4.9,
    imageUrl: 'https://img.youtube.com/vi/FTFaQWZBqQ8/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Figma Interface Overview', duration: '1h'),
      Lesson(title: 'Creating Your First Design', duration: '2h'),
    ],
    price: 59.99,
  ),
  Course(
    title: 'Photography Basics',
    duration: '5h 20min',
    lessonCount: 20,
    rating: 4.7,
    imageUrl: 'https://img.youtube.com/vi/V7z7BAZdt2M/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Camera Settings', duration: '30min'),
      Lesson(title: 'Lighting Techniques', duration: '1h'),
    ],
    price: 39.99,
  ),
  // Course(
  //   title: 'Digital Marketing 101',
  //   duration: '7h 45min',
  //   lessonCount: 25,
  //   rating: 4.6,
  //   imageUrl: 'https://img.youtube.com/vi/SZEDZqIKIJ8/maxresdefault.jpg',
  //   lessons: [
  //     Lesson(title: 'SEO Basics', duration: '1h'),
  //     Lesson(title: 'Social Media Strategies', duration: '1h 30min'),
  //   ],
  //   price: 44.99,
  // ),
  // Add more courses here
  Course(
    title: 'Python Programming',
    duration: '10h',
    lessonCount: 40,
    rating: 4.9,
    imageUrl: 'https://img.youtube.com/vi/kqtD5dpn9C8/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Introduction to Python', duration: '1h'),
      Lesson(title: 'Data Structures', duration: '2h'),
    ],
    price: 69.99,
  ),
  Course(
    title: 'Graphic Design Basics',
    duration: '8h',
    lessonCount: 30,
    rating: 4.5,
    imageUrl: 'https://img.youtube.com/vi/WONZVnlam6U/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Color Theory', duration: '1h'),
      Lesson(title: 'Typography', duration: '1h 30min'),
    ],
    price: 59.99,
  ),
  Course(
    title: 'JavaScript Essentials',
    duration: '9h',
    lessonCount: 35,
    rating: 4.7,
    imageUrl: 'https://img.youtube.com/vi/W6NZfCO5SIk/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'JS Basics', duration: '1h'),
      Lesson(title: 'DOM Manipulation', duration: '1h 30min'),
    ],
    price: 64.99,
  ),
  Course(
    title: 'Data Science with R',
    duration: '12h',
    lessonCount: 50,
    rating: 4.8,
    imageUrl: 'https://img.youtube.com/vi/ZXrHkIz-krE/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'R Basics', duration: '1h'),
      Lesson(title: 'Data Visualization', duration: '2h'),
    ],
    price: 79.99,
  ),
  Course(
    title: 'Machine Learning A-Z',
    duration: '15h',
    lessonCount: 60,
    rating: 4.9,
    imageUrl: 'https://img.youtube.com/vi/GwIo3gDZCVQ/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Supervised Learning', duration: '2h'),
      Lesson(title: 'Unsupervised Learning', duration: '2h 30min'),
    ],
    price: 89.99,
  ),
  Course(
    title: 'Blockchain Basics',
    duration: '6h',
    lessonCount: 20,
    rating: 4.6,
    imageUrl: 'https://img.youtube.com/vi/gyMwXuJrbJQ/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Introduction to Blockchain', duration: '1h'),
      Lesson(title: 'Smart Contracts', duration: '1h 30min'),
    ],
    price: 54.99,
  ),
  Course(
    title: 'Cybersecurity Fundamentals',
    duration: '8h',
    lessonCount: 30,
    rating: 4.7,
    imageUrl: 'https://img.youtube.com/vi/bPVaOlJ6ln0/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Network Security', duration: '1h'),
      Lesson(title: 'Cryptography', duration: '1h 30min'),
    ],
    price: 64.99,
  ),
  Course(
    title: 'Artificial Intelligence',
    duration: '14h',
    lessonCount: 55,
    rating: 4.9,
    imageUrl: 'https://img.youtube.com/vi/JMUxmLyrhSk/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'AI Basics', duration: '1h'),
      Lesson(title: 'Neural Networks', duration: '2h'),
    ],
    price: 94.99,
  ),
  Course(
    title: 'Cloud Computing',
    duration: '10h',
    lessonCount: 40,
    rating: 4.8,
    imageUrl: 'https://img.youtube.com/vi/2LaAJq1lB1Q/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'AWS Basics', duration: '1h'),
      Lesson(title: 'Azure Fundamentals', duration: '1h 30min'),
    ],
    price: 74.99,
  ),
  Course(
    title: 'DevOps Essentials',
    duration: '9h',
    lessonCount: 35,
    rating: 4.7,
    imageUrl: 'https://img.youtube.com/vi/Xrgk023l4lI/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'CI/CD Pipelines', duration: '1h'),
      Lesson(title: 'Docker & Kubernetes', duration: '2h'),
    ],
    price: 69.99,
  ),
  Course(
    title: 'Mobile App Development',
    duration: '11h',
    lessonCount: 45,
    rating: 4.8,
    imageUrl: 'https://img.youtube.com/vi/x0uinJvhNxI/maxresdefault.jpg',
    lessons: [
      Lesson(title: 'Flutter Basics', duration: '1h'),
      Lesson(title: 'React Native', duration: '1h 30min'),
    ],
    price: 79.99,
  ),
];
