import 'package:design_ideaz_app/screens/course_overview_screen.dart';

final List<Course> courses = [
  Course(
    title: 'Web design fundamentals',
    duration: '8h 30min',
    lessonCount: 32,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x400/90EE90/ffffff/png?text=Web+Design+Course',
    lessons: [
      Lesson(title: 'Introduction to Web Design', duration: '45min'),
      Lesson(title: 'HTML Basics', duration: '1h 30min'),
    ],
    price: 49.99,
  ),
  Course(
    title: 'Figma Master Class',
    duration: '6h30m',
    lessonCount: 28,
    rating: 4.9,
    imageUrl: 'https://placehold.co/600x400/87CEEB/ffffff/png?text=UI+Design+Course',
    lessons: [
      Lesson(title: 'Figma Interface Overview', duration: '1h'),
      Lesson(title: 'Creating Your First Design', duration: '2h'),
    ],
    price: 59.99,
  ),
  Course(
    title: 'Photography Basics',
    duration: '5h 20min',
    lessonCount: 20,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x400/FFD700/ffffff/png?text=Photography+Course',
    lessons: [
      Lesson(title: 'Camera Settings', duration: '30min'),
      Lesson(title: 'Lighting Techniques', duration: '1h'),
    ],
    price: 39.99,
  ),
  Course(
    title: 'Digital Marketing 101',
    duration: '7h 45min',
    lessonCount: 25,
    rating: 4.6,
    imageUrl: 'https://placehold.co/600x400/FF6347/ffffff/png?text=Marketing+Course',
    lessons: [
      Lesson(title: 'SEO Basics', duration: '1h'),
      Lesson(title: 'Social Media Strategies', duration: '1h 30min'),
    ],
    price: 44.99,
  ),
  // Add more courses here
  Course(
    title: 'Python Programming',
    duration: '10h',
    lessonCount: 40,
    rating: 4.9,
    imageUrl: 'https://placehold.co/600x400/4682B4/ffffff/png?text=Python+Course',
    lessons: [
      Lesson(title: 'Introduction to Python', duration: '1h'),
      Lesson(title: 'Data Structures', duration: '2h'),
    ],
    price: 69.99,
  ),
  Course(
    title: 'Graphic Design Basics',
    duration: '8h',
    lessonCount: 30,
    rating: 4.5,
    imageUrl: 'https://placehold.co/600x400/FF69B4/ffffff/png?text=Graphic+Design+Course',
    lessons: [
      Lesson(title: 'Color Theory', duration: '1h'),
      Lesson(title: 'Typography', duration: '1h 30min'),
    ],
    price: 59.99,
  ),
  Course(
    title: 'JavaScript Essentials',
    duration: '9h',
    lessonCount: 35,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x400/32CD32/ffffff/png?text=JavaScript+Course',
    lessons: [
      Lesson(title: 'JS Basics', duration: '1h'),
      Lesson(title: 'DOM Manipulation', duration: '1h 30min'),
    ],
    price: 64.99,
  ),
  Course(
    title: 'Data Science with R',
    duration: '12h',
    lessonCount: 50,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x400/8A2BE2/ffffff/png?text=Data+Science+Course',
    lessons: [
      Lesson(title: 'R Basics', duration: '1h'),
      Lesson(title: 'Data Visualization', duration: '2h'),
    ],
    price: 79.99,
  ),
  Course(
    title: 'Machine Learning A-Z',
    duration: '15h',
    lessonCount: 60,
    rating: 4.9,
    imageUrl: 'https://placehold.co/600x400/FF4500/ffffff/png?text=Machine+Learning+Course',
    lessons: [
      Lesson(title: 'Supervised Learning', duration: '2h'),
      Lesson(title: 'Unsupervised Learning', duration: '2h 30min'),
    ],
    price: 89.99,
  ),
  Course(
    title: 'Blockchain Basics',
    duration: '6h',
    lessonCount: 20,
    rating: 4.6,
    imageUrl: 'https://placehold.co/600x400/00CED1/ffffff/png?text=Blockchain+Course',
    lessons: [
      Lesson(title: 'Introduction to Blockchain', duration: '1h'),
      Lesson(title: 'Smart Contracts', duration: '1h 30min'),
    ],
    price: 54.99,
  ),
  Course(
    title: 'Cybersecurity Fundamentals',
    duration: '8h',
    lessonCount: 30,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x400/FF8C00/ffffff/png?text=Cybersecurity+Course',
    lessons: [
      Lesson(title: 'Network Security', duration: '1h'),
      Lesson(title: 'Cryptography', duration: '1h 30min'),
    ],
    price: 64.99,
  ),
  Course(
    title: 'Artificial Intelligence',
    duration: '14h',
    lessonCount: 55,
    rating: 4.9,
    imageUrl: 'https://placehold.co/600x400/FF1493/ffffff/png?text=AI+Course',
    lessons: [
      Lesson(title: 'AI Basics', duration: '1h'),
      Lesson(title: 'Neural Networks', duration: '2h'),
    ],
    price: 94.99,
  ),
  Course(
    title: 'Cloud Computing',
    duration: '10h',
    lessonCount: 40,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x400/1E90FF/ffffff/png?text=Cloud+Computing+Course',
    lessons: [
      Lesson(title: 'AWS Basics', duration: '1h'),
      Lesson(title: 'Azure Fundamentals', duration: '1h 30min'),
    ],
    price: 74.99,
  ),
  Course(
    title: 'DevOps Essentials',
    duration: '9h',
    lessonCount: 35,
    rating: 4.7,
    imageUrl: 'https://placehold.co/600x400/228B22/ffffff/png?text=DevOps+Course',
    lessons: [
      Lesson(title: 'CI/CD Pipelines', duration: '1h'),
      Lesson(title: 'Docker & Kubernetes', duration: '2h'),
    ],
    price: 69.99,
  ),
  Course(
    title: 'Mobile App Development',
    duration: '11h',
    lessonCount: 45,
    rating: 4.8,
    imageUrl: 'https://placehold.co/600x400/FF4500/ffffff/png?text=Mobile+App+Course',
    lessons: [
      Lesson(title: 'Flutter Basics', duration: '1h'),
      Lesson(title: 'React Native', duration: '1h 30min'),
    ],
    price: 79.99,
  ),
];
